#IMAGEM BASE NODE:14
FROM node:14
#WORKDIR É O DIRETORIO PADRÃO ONDE VAI RODAR OS COMANDOS E INSTANCIAR O CONTAINER
WORKDIR /app-node
#CRIA UMA VARIAVEL CHAMADA PORT_BUILD EM TEMPO DE CRIAÇÃO DA IMAGEM
ARG PORT_BUILD=6000
#CRIA UMA VARIAVEL DE AMBIENTE DENOMINADA PORT EM TEMPO DE EXECUÇÃO DO CONTAINER
ENV PORT=$PORT_BUILD
#EXPÕE A PORTA QUE É PASSADA COMO VARIAVEL DE AMBIENTE DENOMINADA PORTA
EXPOSE $PORT
#COPY É UTILIZADO PARA COPIAR OS ARQUIVOS DE UM DIRETÓRIO DO HOST PRO GUEST
#NESSE CASO ESTA COPIANDO DO DIRETORIO DO DOCKERFILE PARA O WORKDIR DA IMAGEM
COPY . .
#RUN É O COMANDO RODADO EM TEMPO DE BUILD DA IMAGEM
RUN npm install
#ENTRYPOINT É O COMANDO RODADO EM TEMPO DE EXECUÇÃO
#DO CONTAINER
ENTRYPOINT npm start